module.exports = {
  CAMBIAR_DIALOG_ACTION: 'CAMBIAR_DIALOG_ACTION',
  CAMBIAR_PAGE_ACTION: 'CAMBIAR_PAGE_ACTION',
  CERRAR_DIALOG_CON_MSG_ACTION: 'CERRAR_DIALOG_CON_MSG_ACTION',
  ABRIR_LINK_CON_SNACKBAR: 'ABRIR_LINK_CON_SNACKBAR',
  MOSTRAR_ERROR_CON_SNACKBAR: 'MOSTRAR_ERROR_CON_SNACKBAR',
};
