export const CAMBIAR_DIALOG_ACTION = 'CAMBIAR_DIALOG_ACTION';
export const CAMBIAR_PAGE_ACTION = 'CAMBIAR_PAGE_ACTION';
export const CERRAR_DIALOG_CON_MSG_ACTION = 'CERRAR_DIALOG_CON_MSG_ACTION';
export const ABRIR_LINK_CON_SNACKBAR = 'ABRIR_LINK_CON_SNACKBAR';
export const MOSTRAR_ERROR_CON_SNACKBAR = 'MOSTRAR_ERROR_CON_SNACKBAR';
