export const CLIENTE_DIALOG = 'CLIENTE_DIALOG';
export const PRODUCTO_DIALOG = 'PRODUCTO_DIALOG';
export const MEDICO_DIALOG = 'MEDICO_DIALOG';
export const PAGOS_DIALOG = 'PAGOS_DIALOG';
export const NUEVO_MEDICO_DIALOG_CLOSED = 'NUEVO_MEDICO_DIALOG_CLOSED';
