export const CAMBIAR_DIALOG_ACTION = 'CAMBIAR_DIALOG_ACTION'
export const CERRAR_DIALOG_CON_MSG_ACTION = 'CERRAR_DIALOG_CON_MSG_ACTION'
export const ABRIR_LINK_CON_SNACKBAR = 'ABRIR_LINK_CON_SNACKBAR'
