export const NUEVO_CLIENTE_DIALOG = 'NUEVO_CLIENTE_DIALOG'
export const NUEVO_CLIENTE_DIALOG_CLOSED = 'NUEVO_CLIENTE_DIALOG_CLOSED'
export const NUEVO_PRODUCTO_DIALOG = 'NUEVO_PRODUCTO_DIALOG'
export const NUEVO_PRODUCTO_DIALOG_CLOSED = 'NUEVO_PRODUCTO_DIALOG_CLOSED'
