module.exports = {
  FACTURA_LIST_PAGE : 'FACTURA_LIST_PAGE',
  NEW_FACTURA_PAGE : 'NEW_FACTURA_PAGE',
  NEW_FACTURA_EXAMEN_PAGE : 'NEW_FACTURA_EXAMEN_PAGE',
  EDITAR_FACTURA_PAGE : 'EDITAR_FACTURA_PAGE',
  EDITAR_FACTURA_EXAMEN_PAGE : 'EDITAR_FACTURA_EXAMEN_PAGE',
}
